// <auto-generated />
namespace TokenAuthApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addinguserandemployeemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addinguserandemployeemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202305131135413_adding user and employee model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
